apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
    app: myservice
spec:
  selector:
    app: myservice
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: ClusterIP
