apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myservice-servicemonitor
  labels:
    release: kube-prometheus   # see note below
spec:
  selector:
    matchLabels:
      app: myservice
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
